# Fly.io application configuration for Astro portfolio website

[app]
name = "portfolio-app"
primary_region = "sea"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[build]
  dockerfile = "Dockerfile"

[env]
  NODE_ENV = "production"
  PORT = "3000"
  HOST = "0.0.0.0"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  # Health check for the application
  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/"
    headers = {}

  # Additional health check for static assets
  [[http_service.checks]]
    grace_period = "5s"
    interval = "60s"
    method = "GET"
    timeout = "3s"
    path = "/favicon.svg"
    headers = {}

[vm]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256

[deploy]
  release_command = "echo 'Starting Astro portfolio deployment...'"
  strategy = "rolling"

# Security headers and HTTPS enforcement
[[http_service.response_headers]]
  "X-Frame-Options" = "DENY"
  "X-Content-Type-Options" = "nosniff"
  "X-XSS-Protection" = "1; mode=block"
  "Referrer-Policy" = "strict-origin-when-cross-origin"
  "Content-Security-Policy" = "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self'; connect-src 'self'"