name: PR Validation

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  validate:
    name: Validate Pull Request
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: TypeScript checking
        run: npm run check
        
      - name: Build for production
        run: npm run build
        
      - name: Start preview server and run performance tests
        run: |
          npm run preview &
          sleep 10
          npm run test:e2e
          pkill -f 'astro preview' || true